### ISSUE TITLE
Can you add a method to close the keyboard?

### ISSUE THREAD

**Issue by osdio** [johanneslumpe/react-native-keyboardevents#14]

**Comment by johanneslumpe** [comment]
I'll have to look into this, though from my understanding it is the responsibility of the text field or its delegate to close the keyboard. You usually hide the keyboard by ending editing using `[self.view endEditing:YES];` or `[UIResponder resignFirstResponder]` in obj-c. I haven't checked whether there is an equivalent available in react-native.

**Comment by josebalius** [comment]
@soliury you might be able to call "blur()" on the text field to close it

Example:

```
<TextInput ref="myInput" />

this.refs.myInput.blur();
```

**Comment by osdio** [comment]
@johanneslumpe Ok, it works. Thank you.

**Comment by johanneslumpe** [comment]
:+1:
