### ISSUE TITLE
Please update to react-native 0.7.0

### ISSUE THREAD

**Issue by osdio** [johanneslumpe/react-native-keyboardevents#17]

**Comment by johanneslumpe** [comment]
Can you be more specific about this? Does an error occur when using this module with 0.7? I haven't had the time to test it yet.

**Comment by isair** [comment]
I'm using this package with react-native 0.7.1 and haven't run into any problems preventing it from working.

**Comment by osdio** [comment]
Sorry, it's the problem of another package. Sorry for that.

**Comment by johanneslumpe** [comment]
@isair Thanks for confirming! @soliury np :)
