### ISSUE TITLE
Update spacer height on 'interactive' keyboard close.

### ISSUE THREAD

**Issue by irfaan** [johanneslumpe/react-native-keyboardevents#18]
When using `keyboardDismissMode="interactive"`, the keyboard will slide down at the same rate at which I slide content past it. Is there a method that can set the spacer height dynamically when the keyboard is being dismissed this way?

**Comment by johanneslumpe** [comment]
Have you tried to use the `WillChangeFrame` and `DidChangeFrame` events? Maybe they get triggered when you slide down the keyboard, since it's constantly changing its frame. Apart from those I currently see no option to do what you're asking for. I'd have to investigate further.

**Comment by irfaan** [comment]
Just tried it. Neither actually seem to fire at all.

**Comment by johanneslumpe** [comment]
Did you use `WillChangeFrame` or the actual event constant? I just shortened them up there. As per readme:

``` javascript
KeyboardEventEmitter.on(KeyboardEvents.KeyboardWillChangeFrame, (frames) => {
  console.log('will change', frames);
});

KeyboardEventEmitter.on(KeyboardEvents.KeyboardDidChangeFrame, (frames) => {
  console.log('did change', frames);
});
```

Did you try that?

**Comment by irfaan** [comment]
Yes - I had actually copied them directly from the readme. No console messages appearing on drag of the keyboard or when its open or dismissed.

Right now, trying to determine if this can help at all: http://stackoverflow.com/questions/24634795/keyboard-handling-just-like-in-messages-app-in-ios-7
Thoughts?

**Comment by johanneslumpe** [comment]
Well that just points out that it should trigger a `UIKeyboardDidChangeFrameNotification` notification, for which the lib is already listening [here](https://github.com/johanneslumpe/react-native-keyboardevents/blob/master/RNKeyboardEventsManager.m#L48). I'd have to try this out myself, but I have no time currently. According to the stackoverflow link, it should actually be triggered for interactive dismissal.

**Comment by irfaan** [comment]
The event wasn't firing because it is misnamed. Pull request for Readme here: https://github.com/johanneslumpe/react-native-keyboardevents/pull/19

Also, seems like it doesn't fire while the keyboard is being dismissed.

**Comment by johanneslumpe** [comment]
Oh, duh! Glad you figured it out :)

**Comment by irfaan** [comment]
Any ideas on how to get the keyboard position for interactive dismissal?

Something here, maybe? http://stackoverflow.com/questions/19118921/moving-a-bar-with-uiscrollviewkeyboarddismissmodeinteractive

Whenever you have a moment to check it out - don't rush on my account. Thank you for the plugin and your continued help here!
