### ISSUE TITLE
how can i get keyboard height

### ISSUE THREAD

**Issue by ericzwong** [johanneslumpe/react-native-keyboardevents#2]
The Keyboard will cover the textinput , so how can i get keyboard height

**Comment by johanneslumpe** [comment]
You can get the height of the keyboard, by inspecting the argument the event handler receives. It contains `begin` and `end` objects, which each contain the appropriate data for the keyboard frame before and after the animation. You most likely want to use `frames.end.height`.

**Comment by ericzwong** [comment]
en ha ! that is very nice for me
