### ISSUE TITLE
Errors with 0.7.1 release.

### ISSUE THREAD

**Issue by piyushchauhan2011** [johanneslumpe/react-native-keyboardevents#20]
![screen shot 2015-07-16 at 7 45 07 pm](https://cloud.githubusercontent.com/assets/693487/8720007/384787ac-2bf3-11e5-8961-aea7c7ce11ed.png)

**Comment by johanneslumpe** [comment]
@piyushchauhan2011 You included the static library and this shows up? If so I'll have to investigate that. Didn't yet try out 0.7.1

**Comment by johanneslumpe** [comment]
@piyushchauhan2011 I just checked the project against `0.7.1.` - it works as expected. I used the demo code from the readme and it worked just fine. This does not seem to be an error with the lib, but rather with your local code (the way you require the lib, or that you are missing the static library). Please control everything. If you cannot figure it out, please post back here

**Comment by piyushchauhan2011** [comment]
```
var KeyboardEvents = require('react-native-keyboardevents');
var KeyboardEventEmitter = KeyboardEvents.Emitter;

KeyboardEventEmitter.on(KeyboardEvents.KeyboardWillShowEvent, (frames) => {
  console.log('will show', frames);
});
```

I'm using this code.

**Comment by piyushchauhan2011** [comment]
I also created a brand new project.
Did `npm install react-native-keyboardevents --save`
and copy pasted the code

```
var KeyboardEvents = require('react-native-keyboardevents');
var KeyboardEventEmitter = KeyboardEvents.Emitter;

KeyboardEventEmitter.on(KeyboardEvents.KeyboardWillShowEvent, (frames) => {
  console.log('will show', frames);
});
```

Got this error...
![screen shot 2015-07-17 at 12 03 06 pm](https://cloud.githubusercontent.com/assets/693487/8739184/f2efff84-2c7b-11e5-8589-2a66b0d404b8.png)

**Comment by piyushchauhan2011** [comment]
I'm really sorry did silly mistake, works fine. :+1:
