### ISSUE TITLE
can't find module react-native

### ISSUE THREAD

**Issue by phillyqueso** [johanneslumpe/react-native-keyboardevents#22]
I'm making a cocoapod static lib that uses react-native. I have react-native as a cocoapod dependency, and follow your instructions yet I get a failure to include react-native from your module.

This is more of a feature request; I guess. Could this also be a cocoapod, so I could add it as a dependency that way?

Let me know if I can help. Thanks!

**Comment by johanneslumpe** [comment]
I don't think this is something that is going to happen, as this module will be obsolete for react-native 0.11. As of that version keyboard events will be supported directly by react-native. So I am not sure whether it is really necessary to add a pod for this library.

**Comment by phillyqueso** [comment]
Ah, right on...

**Comment by nicholasstephan** [comment]
I'm looking at react native 0.11 now, but don't see any mention of keyboard events. Did they make it in there? Do you know where they're documented? Thanks.

**Comment by johanneslumpe** [comment]
@nicholasstephan sorry I cannot tell you that, as I didn't take a closer look at 0.11 yet. But I assume you can still use this package to get keyboard events!
