### ISSUE TITLE
Example doesn't work properly on Android

### ISSUE THREAD

**Issue by iheart2code** [johanneslumpe/react-native-keyboardevents#30]
Consider changing your example from `keyboardWillHide` to `keyboardDidHide`, since Android doesn't dispatch the willHide event.

**Comment by johanneslumpe** [comment]
@iheart2code Notice the info at the top of the readme that this module is obsolete. It should not be used anymore.

**Comment by iheart2code** [comment]
OK, but the example you provide right below that statement doesn't work on Android.
