### ISSUE TITLE
How to TextInput and keyboard sync move?

### ISSUE THREAD

**Issue by Iliker** [johanneslumpe/react-native-keyboardevents#4]
I tried it， It seems that keyboard pops up after, TextInput will appear

Please, how to TextInput and keyboard sync move?

**Comment by johanneslumpe** [comment]
You can use the experimental animation API or you should be able to increment the view's height based on the animation duration and thus achieve a smooth transition. I'll see if I get time soon to add that to the example.

**Comment by Iliker** [comment]
ok, thanks~

**Comment by irfaan** [comment]
@johanneslumpe any chance you had time to add the animated spacer to the example but forgot to merge? :dancer:
