### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by ele828** [johanneslumpe/react-native-keyboardevents#5]
I met a problem

`undefined is not an object(evaluating 'RNKeyboardEventsManager.KeyboardWillShow')`

I don't know what cause this.

**Comment by johanneslumpe** [comment]
There is no such property. If you are searching for the event, please try

``` javascript
var KeyboardEvents = require('react-native-keyboardevents');
console.log(KeyboardEvents.KeyboardWillShowEvent);
```

You should check out the example in the readme file. It explains how to use the plugin ;)

**Comment by ele828** [comment]
Yeah, I dit it by README. And I tried your code...also get the error...I don't know why?
![pic](http://i2.tietuku.com/d4ac7b8beeab6b4d.png)

**Comment by johanneslumpe** [comment]
Did you add the library to your Xcode project?

**Comment by ele828** [comment]
Oh dear...okay.Solved it. Thank you very much...I ignore that part of words which is not very clear to me.
It works very well now with some animation from `react-tween-state` :+1:

**Comment by danielleknudson** [comment]
I just followed all the directions in the README to add the library to my Xcode project. However, when I add `require('react-native-keyboardevents')` and rebuild/run my app in the iOS Simulator, I get the following error:

```
Error: Cannot read property 'KeyboardWillShow' of undefined
 stack: 
  <unknown>  index.ios.bundle:43198
  <unknown>  index.ios.bundle:43197
  require    index.ios.bundle:244
  <unknown>  index.ios.bundle:43114
  require    index.ios.bundle:244
  <unknown>  index.ios.bundle:42991
  require    index.ios.bundle:244
  <unknown>  index.ios.bundle:42271
  require    index.ios.bundle:244
 URL: undefined
 line: undefined
 message: Cannot read property 'KeyboardWillShow' of undefined
```

Any insights on what I'm doing wrong??

**Comment by johanneslumpe** [comment]
@danielleknudson Did you add the static library to your project?

**Comment by danielleknudson** [comment]
Sorry for the delayed reply.  Thanks for following up. I'll try going through the installation process again and make sure I have the static library in my project. I'll write back if I encounter the same trouble.
