### ISSUE TITLE
Add change event

### ISSUE THREAD

**Issue by magicismight** [johanneslumpe/react-native-keyboardevents#8]
It would be nice to add `UIKeyboardWillChangeFrameNotification` and `UIKeyboardDidChangeFrameNotification` event notification.

**Comment by johanneslumpe** [comment]
I will add these asap @magicismight

**Comment by johanneslumpe** [comment]
@magicismight I see you already forked and added them - care to submit a PR?

**Comment by magicismight** [comment]
@johanneslumpe  Yes, right away

**Comment by johanneslumpe** [comment]
@magicismight has been added with 4cb8c8ab3916f449fa92e236a77e061137bc02ae, new version 0.4.0 is on npm!
